# This rule is not used by the project 03-app-with-db-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over minds.co.minds.co.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: 03-app-with-db-crd
    app.kubernetes.io/managed-by: kustomize
  name: appwithdb-admin-role
rules:
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs
  verbs:
  - '*'
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs/status
  verbs:
  - get
