# This rule is not used by the project 03-app-with-db-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the minds.co.minds.co.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: 03-app-with-db-crd
    app.kubernetes.io/managed-by: kustomize
  name: appwithdb-editor-role
rules:
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs/status
  verbs:
  - get
