---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs/finalizers
  verbs:
  - update
- apiGroups:
  - minds.co.minds.co
  resources:
  - appwithdbs/status
  verbs:
  - get
  - patch
  - update
